---
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - '*.spec'
    - 'Rakefile'

# Rails:
#   Enabled: true
#   TargetRailsVersion: 6.0

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Layout/LineLength:
  Max: 190

# Rails/SkipsModelValidations:
#   Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Max: 45
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'
    - 'app/controllers/concerns/foreman/**/*'
